name: Frontend tests
on:
  pull_request:
  workflow_call:

defaults:
  run:
    working-directory: frontend

jobs:
  unit-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        run: corepack enable
      - name: prepare
        run: yarn install
      - name: test
        run: yarn test
